# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd87cf0b6c49964a60f74502b0c7edb6f3b84b5c13dde9780d09983dca1b9fe43ae0c9785427891539d9e35e5bc445f60391bba8e0c834a619ac01693a2bf073

test:
  secret_key_base: 1238881128b4d3eb1fb3d78f0ab3152c6cd56480f521d6ecc3c744222db8697fdb8bdb2a3be7e71d05472fa28e6f1eab45af4b983286e0835bee2238282fabf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
